os: Visual Studio 2019

environment:
  matrix:
  #- platform: Win32
  #  compiler: "Visual Studio 14 2015"
  #  configuration: Debug
  - platform: x64
    compiler: "Visual Studio 16 2019"
    configuration: Release
    release_arch: "Windows-amd64-32"

install:
  - git submodule update --init --recursive
  - curl -L https://github.com/CICM/pd-faustgen/releases/download/v0.0.0/llvm-9.0.0-windows-x64-mt.zip -o llvm.zip
  - 7z x llvm.zip
  - curl http://faust.grame.fr/images/faust-quick-reference.pdf -o ./external/faust-quick-reference.pdf
build_script:
  - mkdir build && cd build
  - cmake .. -G "%compiler%" -A x64 -DUSE_LLVM_CONFIG=off -DLLVM_DIR=./llvm/lib/cmake/llvm
  - msbuild faustgen~.sln /nologo /p:config=%configuration% /p:plateform=%platform%
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - del /F /Q llvm.zip
  - del /F /S /Q /A external\*.pdb
  - del /F /S /Q /A external\*.ilk
  - del /F /S /Q /A external\*.lib
  - del /F /S /Q /A external\*.exp
  - copy README.md external\README.md
  - copy LICENSE external\LICENSE.txt
  - xcopy /S /E /Y /I .\faust\libraries .\external\libs
  - xcopy /S /E /Y /I .\src .\external\sources
  - attrib +R external\.default.dsp
  - rename external faustgen~
  - 7z a "faustgen_tilde-%release_arch%-sources.zip" faustgen~

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  prerelease: true
  overwrite: true
  draft: true
  auth_token:
    secure: 0Vv/0e24P2Oa/R/obFQBd824WDpAolXToTc1B0xOjM8TdXXkFdRkfRkPHDgCtoCR
  artifact: /.*\.zip/
  on:
    appveyor_repo_tag: true

notifications:

  - provider: Email
    on_build_status_changed: false
